DROP TABLE IF EXISTS scouts, achievements;

CREATE TABLE scouts(
  scout_id SERIAL PRIMARY KEY,
  name varchar(255),
  age integer,
  image varchar(255)
);

CREATE TABLE achievements (
  ach_id serial PRIMARY KEY,
  ach_name varchar(255),
  comp_date varchar(255),
  scout_id integer
  REFERENCES scouts(scout_id) ON DELETE CASCADE
);

INSERT INTO scouts (name, age, image)
VALUES ('Anakin Skywalker', 9, 'images/anakin.png' ),
  ('Obi-Wan Kenobi', 10, 'images/obi-wan-kenobi.png'),
  ('Depa Billaba', 10, 'images/depa-billaba.png'),
  ('Kit Fisto', 9, 'images/Kit-Fisto.png'),
  ('Adi Gallia', 9, 'images/Adi-Gallia.png'),
  ('Qui-Gon Jinn', 10, 'images/qui-gon-jinn.png'),
  ('Mace Windu', 9, 'images/Mace-Windu.png'),
  ('Plo Koon', 10, 'images/plo-koon.png'),
  ('Luminara Unduli', 9, 'images/luminara-undulli.png'),
  ('Even Piell', 9, 'images/Even-Piell.png'),
  ('Yarael Poof', 10, 'images/Yarael-Poof.png'),
  ('Oppo Rancisis', 10, 'images/oppo-rancisis.png'),
  ('Shaak Ti', 9, 'images/shaak-ti.png'),
  ('Quinlan Vos', 9, 'images/quinlan-vos.png'),
  ('Barriss Offee', 9, 'images/Barriss-Offee.png');

  INSERT INTO achievements (ach_name, comp_date, scout_id)
  VALUES ('Webelos Walkabout', '', 1),
  ('First Responder', '', 1),
  ('Stronger, Faster, Higher', '', 1),
  ('Cast Iron Chef', '', 1),
  ('Duty to God and You', '', 1),
  ('Webelos Walkabout', '', 2),
  ('First Responder', '', 2),
  ('Stronger, Faster, Higher', '', 2),
  ('Cast Iron Chef', '', 2),
  ('Duty to God and You', '', 2),
  ('Webelos Walkabout', '', 3),
  ('First Responder', '', 3),
  ('Stronger, Faster, Higher', '', 3),
  ('Cast Iron Chef', '', 3),
  ('Duty to God and You', '', 3),
  ('Webelos Walkabout', '', 4),
  ('First Responder', '', 4),
  ('Stronger, Faster, Higher', '', 4),
  ('Cast Iron Chef', '', 4),
  ('Duty to God and You', '', 4),
  ('Webelos Walkabout', '', 5),
  ('First Responder', '', 5),
  ('Stronger, Faster, Higher', '', 5),
  ('Cast Iron Chef', '', 5),
  ('Duty to God and You', '', 5),
  ('Webelos Walkabout', '', 6),
  ('First Responder', '', 6),
  ('Stronger, Faster, Higher', '', 6),
  ('Cast Iron Chef', '', 6),
  ('Duty to God and You', '', 6),
  ('Webelos Walkabout', '', 7),
  ('First Responder', '', 7),
  ('Stronger, Faster, Higher', '', 7),
  ('Cast Iron Chef', '', 7),
  ('Duty to God and You', '', 7),
  ('Webelos Walkabout', '', 8),
  ('First Responder', '', 8),
  ('Stronger, Faster, Higher', '', 8),
  ('Cast Iron Chef', '', 8),
  ('Duty to God and You', '', 8),
  ('Webelos Walkabout', '', 9),
  ('First Responder', '', 9),
  ('Stronger, Faster, Higher', '', 9),
  ('Cast Iron Chef', '', 9),
  ('Duty to God and You', '', 9),
  ('Webelos Walkabout', '', 10),
  ('First Responder', '', 10),
  ('Stronger, Faster, Higher', '', 10),
  ('Cast Iron Chef', '', 10),
  ('Duty to God and You', '', 10),
  ('Webelos Walkabout', '', 11),
  ('First Responder', '', 11),
  ('Stronger, Faster, Higher', '', 11),
  ('Cast Iron Chef', '', 11),
  ('Duty to God and You', '', 11),
  ('Webelos Walkabout', '', 12),
  ('First Responder', '', 12),
  ('Stronger, Faster, Higher', '', 12),
  ('Cast Iron Chef', '', 12),
  ('Duty to God and You', '', 12),
  ('Webelos Walkabout', '', 13),
  ('First Responder', '', 13),
  ('Stronger, Faster, Higher', '', 13),
  ('Cast Iron Chef', '', 13),
  ('Duty to God and You', '', 13),
  ('Webelos Walkabout', '', 14),
  ('First Responder', '', 14),
  ('Stronger, Faster, Higher', '', 14),
  ('Cast Iron Chef', '', 14),
  ('Duty to God and You', '', 14),
  ('Webelos Walkabout', '', 15),
  ('First Responder', '', 15),
  ('Stronger, Faster, Higher', '', 15),
  ('Cast Iron Chef', '', 15),
  ('Duty to God and You', '', 15);
